
SectorPadronization <- function(base_ERP_full){
  
  Setor_levels_labels <- c("Petróleo e Gas"          = "Petroleo e Gas",
                           "Agro e Pesca"            = "Agro e Pesca",
                           "Energia Elétrica"        = "Energia Eletrica",
                           "Finanças e Seguros"      = "Financas e Seguros",
                           "Siderur & Metalur"       = "Siderurgia e Metalurgia",
                           "Máquinas Indust"         = "Maquinas Industriais",
                           "Outros"                  = "Outros",
                           "Transporte Serviç"       = "Transporte Servico",
                           "Comércio"                = "Comercio",
                           "Textil"                  = "Textil",
                           "Construção"              = "Construcao",
                           "Alimentos e Beb"         = "Alimentos e Bebidas",
                           "Telecomunicações"        = "Telecomunicacoes",
                           "Mineração"               = "Mineracao",
                           "Software e Dados"        = "Software e Dados",
                           "Veiculos e peças"        = "Veiculos e pecas",
                           "Química"                 = "Quimica",
                           "Minerais não Met"        = "Minerais nao Metais",
                           "Eletroeletrônicos"       = "Eletroeletronicos",
                           "Papel e Celulose"        = "Papel e Celulose",
                           "Fundos"                  = "Fundos",
                           "Petroleo e Gas"          = "Petroleo e Gas",
                           "Agro e Pesca"            = "Agro e Pesca",
                           "Energia Eletrica"        = "Energia Eletrica",
                           "Financas e Seguros"      = "Financas e Seguros",
                           "Siderurgia e Metalurgia" = "Siderurgia e Metalurgia",
                           "Maquinas Industriais"    = "Maquinas Industriais",
                           "Outros"                  = "Outros",
                           "Transporte Servico"      = "Transporte Servico",
                           "Comercio"                = "Comercio",
                           "Textil"                  = "Textil",
                           "Construcao"              = "Construcao",
                           "Alimentos e Bebidas"     = "Alimentos e Bebidas",
                           "Telecomunicacoes"        = "Telecomunicacoes",
                           "Mineracao"               = "Mineracao",
                           "Software e Dados"        = "Software e Dados",
                           "Veiculos e pecas"        = "Veiculos e pecas",
                           "Quimica"                 = "Quimica",
                           "Minerais nao Metais"     = "Minerais nao Metais",
                           "Eletroeletronicos"       = "Eletroeletronicos",
                           "Papel e Celulose"        = "Papel e Celulose",
                           "Fundos"                  = "Fundos",
                           "Oil & Gas"               = "Petroleo e Gas",
                           "Agri & Fisheries"        = "Agro e Pesca",
                           "Electric Power"          = "Energia Eletrica",
                           "Finance and Insurance"   = "Financas e Seguros",
                           "Basic & Fab Metal"       = "Siderurgia e Metalurgia",
                           "Industrial Machin"       = "Maquinas Industriais",
                           "Other"                   = "Outros",
                           "Transportat Serv"        = "Transporte Servico",
                           "Trade"                   = "Comercio",
                           "Textile"                 = "Textil",
                           "Construction"            = "Construcao",
                           "Food & Beverage"         = "Alimentos e Bebidas",
                           "Telecommunication"       = "Telecomunicacoes",
                           "Mining"                  = "Mineracao",
                           "Software & Data"         = "Software e Dados",
                           "Vehicle & Parts"         = "Veiculos e pecas",
                           "Chemical"                = "Quimica",
                           "Nonmetallic Min"         = "Minerais nao Metais",
                           "Electric Electron"       = "Eletroeletronicos",
                           "Pulp & Paper"            = "Papel e Celulose",
                           "Funds"                   = "Fundos")
  
  base_ERP_full$Setor <- factor(x = base_ERP_full$Setor,
                                levels = names(Setor_levels_labels),
                                labels = Setor_levels_labels)
  
  if(any(is.na(base_ERP_full$Setor))){
    print(base_ERP_full[is.na(base_ERP_full$Setor), ])
    stop("ERRO: SETOR COMO 'NA'!")
  }
  
  return(base_ERP_full)
}